name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: |
          npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: install pw browsers
        run: npx playwright install --with-deps
      - name: e2e test
        run: |
          npm run start-prod &
          npm run test:e2e

  tag_release:
    needs: simple_deployment_pipeline
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  deploy:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    name: Deploy app
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    needs: [simple_deployment_pipeline, tag_release]
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: install and build
        run: |
          npm install
          npm run build
      - name: deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: notify success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          text: A new version was deployed!
          details: To https://full-stack-open-pokedex-cool-fire-3967.fly.dev/
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: notify fail
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ always() && failure() }}
        with:
          severity: error
          text: "Deployment failed"
          details: "Commit ${{ github.sha }} broke it"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
